ChainSafe/ChainGuardian

package.json
src/renderer/services/wallet/eth2.ts
test/unit/HDWallet.spec.ts
yarn.lock

Implemented eth2 keypair generation

---

src/renderer/containers/AddValidator/CheckPassword.tsx
src/renderer/containers/Dashboard/DashboardContainer.tsx
src/renderer/models/account.ts

now working as intended, after deletion, change is dispatched to CGAccount in app state

Fix, Delete validators

---

src/renderer/actions/network.ts
src/renderer/services/docker/chain.ts
src/renderer/services/docker/container.ts
src/renderer/services/docker/docker-registry.ts
src/renderer/services/docker/type.ts
src/renderer/services/docker/utils.ts
test/e2e/services/docker/chain.spec.ts

Connect to beacon chain

---

src/renderer/components/Button/ButtonAction.tsx
test/components/Button.spec.tsx
test/components/CopyField.spec.tsx
test/components/__snapshots__/Button.spec.tsx.snap
test/components/__snapshots__/CopyField.spec.tsx.snap

Fix copy button memory leak and tooltip

---

src/renderer/actions/network.ts
src/renderer/components/Cards/NodeCard.tsx
src/renderer/components/Cards/cards.scss
src/renderer/components/Validator/ValidatorSimple.tsx
src/renderer/components/Validator/validatorsimple.scss
src/renderer/constants/account.ts
src/renderer/constants/action-types.ts
src/renderer/containers/Dashboard/DashboardContainer.tsx
src/renderer/containers/Onboard/Configure/ConfigureBeaconNode.tsx
src/renderer/containers/Onboard/Configure/ConfigureContainer.tsx
src/renderer/containers/Onboard/DepositTx/DepositTxContainer.tsx
src/renderer/models/account.ts
src/renderer/models/beaconNode.ts
src/renderer/models/ssz/types.ts
src/renderer/reducers/network.ts
src/renderer/services/db/api/database.ts
src/renderer/services/db/api/repositories/beaconNode.ts
src/renderer/services/db/schema.ts
src/renderer/services/docker/chain.ts
src/renderer/services/docker/container.ts
test/components/__snapshots__/Cards.spec.tsx.snap
test/components/__snapshots__/Validator.spec.tsx.snap
test/e2e/redux/actions/network.action.spec.ts
test/e2e/redux/actions/register.action.spec.ts

Connect BN validator

---

src/renderer/actions/deposit.ts
src/renderer/services/deposit/ethers.ts
src/renderer/services/eth2/client/interface.ts
src/renderer/services/eth2/client/prysm/beacon.ts
src/renderer/services/eth2/client/prysm/prysm.ts
src/renderer/services/eth2/client/prysm/types.ts
src/renderer/services/validator/status/index.ts
src/renderer/services/validator/status/statuses.ts
test/e2e/services/deposit/UserDeposit.spec.ts
test/unit/eth2/client/prysm/beacon.spec.ts
test/unit/eth2/client/prysm/payloads/validator.json
test/unit/validator/status/index.spec.ts
test/unit/validator/status/util.ts

- extended api client interfaces and implementation
- added function to determine validator status
- missing dashboard integration(probably it's best to refactor dashboard first)
resolves #160

Validator statuses

---

.eslintrc.js
src/main/gui/window.ts
src/renderer/services/docker/chain.ts
src/renderer/services/docker/container.ts
src/renderer/services/docker/docker-registry.ts

Closes #184 
I don't like the code much so creating a draft so I can take a second look tomorrow :)

Close dev dockers

---

src/renderer/components/NetworkDropdown/NetworkDropdown.tsx
src/renderer/containers/Dashboard/DashboardContainer.tsx
src/renderer/containers/Onboard/Configure/ConfigureContainer.tsx
src/renderer/models/account.ts
src/renderer/reducers/network.ts
src/renderer/services/eth2/networks.ts

Dropdown network select

---

src/renderer/reducers/register.ts
test/e2e/redux/reducers/register.reducer.spec.ts

I am not sure how it worked before but probably only with the flow when importing withdrawal key.
Closes #202

Derivation path

---

src/renderer/actions/deposit.ts
src/renderer/services/deposit/utils.ts
test/e2e/redux/actions/deposit.action.spec.ts
test/e2e/services/deposit/DepositTx.spec.ts
test/e2e/services/deposit/UserDeposit.spec.ts

Update signature for DepositData to use computeSigningRoot

---

src/renderer/actions/validator.ts
src/renderer/components/LogStream/logstream.scss
src/renderer/containers/ValidatorDetails/BeaconNode/BeaconNode.scss
src/renderer/containers/ValidatorDetails/ValidatorDetailsContainer.tsx
src/renderer/containers/ValidatorDetails/ValidatorLogs.tsx
src/renderer/reducers/validators.ts
src/renderer/services/docker/chain.ts
src/renderer/services/docker/utils.ts
src/renderer/services/eth2/client/logger.ts

Validator logger

---

src/renderer/actions/validator.ts

Display validator name by index in list

---

src/renderer/services/eth2/networks/schlesi.ts

Add eth1 endpoint to schlesi

---

src/renderer/components/Notification/notification.scss

Fix css for notification level

---

package.json
src/renderer/components/LogStream/LogStream.tsx
src/renderer/containers/ValidatorDetails/BeaconNode/BeaconNode.tsx
src/renderer/containers/ValidatorDetails/ValidatorLogs.tsx
src/renderer/services/docker/chain.ts
src/renderer/services/docker/container.ts
src/renderer/services/docker/utils.ts
src/renderer/services/eth2/client/logger.ts
src/renderer/services/utils/logging/buffered.ts
src/renderer/services/utils/logging/interface.ts
src/renderer/services/utils/queue/fifo.ts
test/e2e/services/docker/chain.spec.ts
test/unit/utils/logging/buffered.spec.ts
test/unit/utils/queue/fifo.spec.ts
yarn.lock

We will now display log history for validators and BNs.
resolves #234

Cache logs

---

src/renderer/actions/network.ts
src/renderer/actions/validator.ts
src/renderer/components/Topbar/Topbar.tsx
src/renderer/constants/routes.ts
src/renderer/containers/Application.tsx
src/renderer/containers/BeaconNodes/BeaconNodeButtons.tsx
src/renderer/containers/BeaconNodes/BeaconNodes.tsx
src/renderer/containers/BeaconNodes/beacon-nodes.scss
src/renderer/containers/Dashboard/DashboardContainer.scss
src/renderer/containers/ValidatorDetails/BeaconNode/BeaconNode.tsx
src/renderer/models/beaconNode.ts
src/renderer/services/eth2/client/lighthouse/lighthouse.ts
src/renderer/services/utils/cmd.ts
src/renderer/services/utils/formatting.ts
src/renderer/style/index.scss

Closes #243 
Things to have in mind:
- Connecting existing validator with a new or existing beacon node. We have no add functionality but we have remove
- Would be nice to unsubscribe from [listening](https://github.com/NodeFactoryIo/ChainGuardian/blob/master/src/renderer/services/eth2/client/lighthouse/lighthouse.ts#L34)

Manage beacon nodes

---

src/renderer/components/Prompt/InputPrompt.tsx
src/renderer/containers/BeaconNodes/BeaconNodeButtons.tsx
src/renderer/containers/BeaconNodes/BeaconNodes.tsx
src/renderer/containers/Dashboard/DashboardContainer.tsx
src/renderer/containers/Onboard/CreatePassword/CreatePasswordContainer.tsx
test/components/__snapshots__/InputPrompt.spec.tsx.snap

Loading on long actions

---

src/renderer/actions/network.ts
src/renderer/components/Cards/NodeCard.tsx
src/renderer/components/ConfigureBeaconNode/ConfigureBeaconNode.tsx
src/renderer/components/ConfigureBeaconNode/InputBeaconNode.tsx
src/renderer/constants/routes.ts
src/renderer/containers/AddBeaconNode/AddBeaconNode.tsx
src/renderer/containers/Application.tsx
src/renderer/containers/BeaconNodes/BeaconNodeButtons.tsx
src/renderer/containers/Onboard/Configure/ConfigureBeaconNode.tsx
src/renderer/containers/Onboard/Configure/ConfigureContainer.tsx
src/renderer/containers/Onboard/OnBoardModal.tsx
src/renderer/containers/Onboard/OnboardContainer.tsx
src/renderer/containers/Validator/Validator.tsx
src/renderer/models/beaconNode.ts
src/renderer/services/db/api/repositories/beaconNode.ts
test/e2e/redux/actions/network.action.spec.ts

Add beacon node

---

src/renderer/components/Button/buttons.scss
src/renderer/components/CopyField/copyfield.scss
src/renderer/components/Modal/modal.scss
src/renderer/containers/AddBeaconNode/AddBeaconNode.tsx
src/renderer/containers/Onboard/OnboardContainer.scss
src/renderer/containers/Onboard/OnboardContainer.tsx
src/renderer/containers/ValidatorDetails/ValidatorLogs.tsx
src/renderer/containers/ValidatorDetails/ValidatorStats/ValidatorStats.tsx

- Closes #237 
- Some other onboarding button related fix
- Remove validator balance mock graph
- Fixed add beacon screen to have background

Fix ui bugs

---

.env.sample
.github/workflows/ci.yaml
package.json
src/main/gui/window.ts
src/main/main.ts
src/main/sentry.ts
src/renderer/actions/register.ts
src/renderer/actions/validator.ts
src/renderer/app.tsx
src/renderer/constants/routes.ts
src/renderer/containers/Onboard/Consent/ConsentContainer.tsx
src/renderer/containers/Onboard/CreatePassword/CreatePasswordContainer.tsx
src/renderer/containers/Onboard/OnboardContainer.tsx
src/renderer/models/settings.ts
src/renderer/models/types/settings.ts
src/renderer/services/utils/reporting.ts
tsconfig.json
webpack.base.config.js
webpack.base.prod.config.js
webpack.main.config.js
webpack.main.prod.config.js
webpack.renderer.config.js
webpack.renderer.prod.config.js
yarn.lock

Add sentry and sourcemaps

---

src/renderer/constants/routes.ts
src/renderer/containers/Application.tsx
src/renderer/containers/AssignBeaconNode/AssignBeaconNode.tsx
src/renderer/containers/AssignBeaconNode/assignBeaconNode.scss
src/renderer/containers/Validator/Validator.tsx
src/renderer/ducks/beacon/selectors.ts
src/renderer/ducks/beacon/slice.ts
src/renderer/ducks/validator/actions.ts
src/renderer/ducks/validator/sagas.ts
src/renderer/ducks/validator/selectors.ts
src/renderer/ducks/validator/slice.ts
src/renderer/models/types/validatorBeaconNodes.ts
src/renderer/models/validatorBeaconNodes.ts
src/renderer/services/db/api/database.ts
src/renderer/services/db/api/repositories/validatorBeaconNodes.ts
src/renderer/services/db/schema.ts
src/renderer/style/index.scss

Beacon assign

---

src/renderer/components/Input/InputForm.tsx
src/renderer/components/Input/inputform.scss
src/renderer/components/KeyModalContent/KeyModalContent.scss
src/renderer/components/KeyModalContent/KeyModalContent.tsx
src/renderer/containers/Onboard/SigningKey/Import/SigningKeyImport.tsx
test/components/KeyModalContent.spec.tsx
test/components/__snapshots__/Input.spec.tsx.snap
test/components/__snapshots__/InputPrompt.spec.tsx.snap
test/components/__snapshots__/KeyModalContent.spec.tsx.snap

Validator count on seed

---

src/renderer/containers/BeaconNodes/BeaconNodes.tsx
src/renderer/ducks/validator/selectors.ts

implement beacon validator list ui

---

src/renderer/components/Loading/loading.scss
src/renderer/containers/AddBeaconNode/AddBeaconNode.tsx
src/renderer/ducks/beacon/actions.ts
src/renderer/ducks/beacon/sagas.ts
src/renderer/ducks/network/actions.ts
src/renderer/ducks/network/sagas.ts
src/renderer/services/docker/container.ts
src/renderer/services/utils/cmd.ts
src/renderer/style/common.scss
test/unit/services/docker/DockerContainer.spec.ts
types/helpers.ts

Cancel docker pull

---

src/renderer/ducks/register/sagas.ts

Fix import keystore

---

src/renderer/components/Accordion/Accordion.tsx
src/renderer/components/Accordion/accordion.scss
src/renderer/components/ConfigureBeaconNode/ConfigureBeaconNode.tsx
src/renderer/style/index.scss

implement accordion

---

src/renderer/models/beaconNode.ts
src/renderer/services/eth2/client/index.ts
src/renderer/services/eth2/client/interface.ts
src/renderer/services/validator/status/index.ts
test/unit/services/eth2/client/mock.ts

Update eth2 api interface

---

src/renderer/components/ConfigureBeaconNode/InputBeaconNode.tsx
src/renderer/containers/BeaconNodes/BeaconNodes.tsx
src/renderer/ducks/beacon/sagas.ts
src/renderer/services/eth2/client/index.ts

Fix add beacon

---

src/renderer/containers/BeaconNodes/BeaconNodes.tsx

Fix beacon node list navigation

---

src/config/config.ts
src/renderer/components/ConfigureBeaconNode/ConfigureBeaconNode.tsx

Set beacon node docker default to home folder

---

mocks/electronMock.ts
package.json
src/main/db/ipc.ts
src/renderer/services/db/controller/ipc.ts
test/unit/db/controller/leveldb.spec.ts
test/unit/models/account.spec.ts
test/unit/services/db/controller/ipc.spec.ts
test/unit/utils/iterable.ts
yarn.lock

- added `electron-mock-ipc`
- added tests for level db controller
- added tests for ipc communication
Resolves #336

Added tests for database and it's communication pipe

---

.env.dist

update docker image

---

src/renderer/containers/BeaconNodes/BeaconNodes.tsx
src/renderer/containers/Validator/Validator.tsx
src/renderer/ducks/beacon/actions.ts
src/renderer/ducks/beacon/sagas.ts
src/renderer/ducks/beacon/slice.ts
src/renderer/ducks/network/types.ts
src/renderer/services/eth2/client/eth2ApiClient/cgEth2EventsApi.ts
src/renderer/services/eth2/client/eth2ApiClient/index.ts
src/renderer/services/eth2/client/interface.ts

Beacon node slot height

---

src/renderer/containers/BeaconNode/BeaconNode.tsx
src/renderer/containers/BeaconNodes/BeaconNodes.tsx

fix crash on remote beacon node details

---

src/renderer/ducks/validator/sagas.ts
src/renderer/services/eth2/client/logger.ts

fix validator logger

---

src/renderer/ducks/beacon/actions.ts
src/renderer/ducks/beacon/sagas.ts
src/renderer/ducks/beacon/slice.ts
src/renderer/ducks/validator/selectors.ts
src/renderer/models/validatorBeaconNodes.ts
src/renderer/services/db/api/repositories/validatorBeaconNodes.ts
src/renderer/services/docker/container.ts

Fix beacon node delete then add

---

src/renderer/components/SimpleLineChart/SimpleLineChart.tsx
src/renderer/containers/ValidatorDetails/ValidatorDetailsContainer.tsx
src/renderer/containers/ValidatorDetails/ValidatorStats/ValidatorStats.tsx
src/renderer/ducks/validator/actions.ts
src/renderer/ducks/validator/sagas.ts
src/renderer/ducks/validator/slice.ts
src/renderer/models/types/validatorBalance.ts
src/renderer/models/validatorBalances.ts
src/renderer/services/db/api/database.ts
src/renderer/services/db/api/repositories/validator/balance.ts
src/renderer/services/db/schema.ts
src/renderer/services/eth2/client/eth2ApiClient/cgEth2BeaconStateApi.ts
src/renderer/services/eth2/client/interface.ts

Validator balance chart

---

src/main/gui/utils.ts
src/main/main.ts
src/renderer/app.tsx
src/renderer/containers/Onboard/SigningKey/Import/SigningKeyImport.tsx
src/renderer/services/eth2/client/eth2ApiClient/cgEth2BeaconApi.ts
src/renderer/services/eth2/client/eth2ApiClient/cgEth2BeaconStateApi.ts
src/renderer/services/eth2/client/eth2ApiClient/cgEth2Config.ts
src/renderer/services/utils/getValidatorStatus.ts
test/screens/setup.ts

change console with electron-log

---

src/renderer/components/ConfigureBeaconNode/InputBeaconNode.tsx

Feedback on beacon node not found

---

src/renderer/constants/validatorStatus.ts
src/renderer/containers/BeaconNodes/BeaconNodeButtons.tsx
src/renderer/ducks/beacon/sagas.ts
src/renderer/ducks/validator/actions.ts
src/renderer/ducks/validator/sagas.ts
src/renderer/ducks/validator/slice.ts
src/renderer/services/eth2/client/eth2ApiClient/cgEth2EventsApi.ts
src/renderer/services/eth2/client/index.ts
src/renderer/services/eth2/client/interface.ts
src/renderer/services/utils/getValidatorStatus.ts

Fix beacon status

---

src/renderer/components/ConfigureBeaconNode/ConfigureDockerPath.tsx
src/renderer/containers/AddBeaconNode/AddBeaconNode.tsx

implement docker set path

---

src/renderer/components/CheckBox/CheckBox.tsx
src/renderer/containers/AssignBeaconNode/AssignBeaconNode.tsx
src/renderer/containers/AssignBeaconNode/assignBeaconNode.scss
src/renderer/ducks/validator/actions.ts
src/renderer/ducks/validator/sagas.ts
src/renderer/services/db/api/repositories/validatorBeaconNodes.ts

Reassign beacon improvment

---

src/renderer/services/eth2/client/index.ts

fix feedback on beacon node not found

---

src/renderer/constants/validatorStatus.ts
src/renderer/containers/Validator/Validator.tsx
src/renderer/ducks/beacon/sagas.ts
src/renderer/ducks/validator/sagas.ts
src/renderer/services/eth2/client/index.ts
src/renderer/services/utils/getValidatorStatus.ts

Live validator status

---

src/renderer/components/Background/background.scss
src/renderer/containers/BeaconNodes/BeaconNodeButtons.tsx
src/renderer/containers/BeaconNodes/BeaconNodeDetailsContainer.tsx
src/renderer/containers/BeaconNodes/BeaconNodes.tsx
src/renderer/containers/ValidatorDetails/ValidatorDetailsContainer.tsx

closes #423 
closes #408 
closes #387

Improve UI

---

src/renderer/DockerDemonNotificator.tsx
src/renderer/app.tsx
src/renderer/components/ConfirmModal/confirmmodal.scss
src/renderer/ducks/beacon/sagas.ts
src/renderer/ducks/network/actions.ts
src/renderer/ducks/network/selectors.ts
src/renderer/ducks/network/slice.ts
src/renderer/ducks/network/types.ts
src/renderer/services/docker/command.ts
src/renderer/services/docker/container.ts
src/renderer/style/base.scss

Docker warning

---

src/renderer/services/docker/command.ts
src/renderer/services/docker/container.ts
src/renderer/services/utils/cmd.ts

Fix beacon node logs

---

src/main/logger/index.ts
src/renderer/containers/BeaconNodes/BeaconNodeButtons.tsx
src/renderer/ducks/beacon/sagas.ts
src/renderer/ducks/validator/sagas.ts
src/renderer/services/db/api/database.ts
src/renderer/services/docker/container.ts
src/renderer/services/eth2/networks/local.ts
src/renderer/services/eth2/networks/pyrmont.ts
src/renderer/services/utils/logging/buffered.ts
src/renderer/services/utils/logging/interface.ts

Fix database clearing

---

src/renderer/components/Button/ButtonAction.tsx
src/renderer/components/Button/buttons.scss
src/renderer/containers/Validator/Validator.tsx
src/renderer/containers/ValidatorDetails/ValidatorStats/ValidatorStats.tsx

UI improvements

---

src/renderer/components/Cards/NodeCard.tsx
src/renderer/containers/BeaconNode/BeaconNode.tsx
src/renderer/containers/BeaconNodes/BeaconNodeButtons.tsx
src/renderer/containers/BeaconNodes/BeaconNodes.tsx
src/renderer/containers/Validator/Validator.tsx
src/renderer/ducks/beacon/slice.ts

Starting beacon node state

---

.env.dist

update lighthouse docker version

---

src/main/logger/index.ts
src/renderer/services/eth2/client/eth2ApiClient/cgEth2ValidatorApi.tsx

implement specific logger for aggregate and proofs

---

package.json
src/renderer/containers/ValidatorDetails/ValidatorStats/ValidatorAttestationEfficiencyChart.tsx
src/renderer/containers/ValidatorDetails/ValidatorStats/ValidatorBalanceChart.tsx
src/renderer/containers/ValidatorDetails/ValidatorStats/ValidatorStats.tsx
src/renderer/models/attestationEffectiveness.ts
src/renderer/services/utils/charts.ts
yarn.lock

Attestation chart

---

src/renderer/components/ConfigureBeaconNode/InputBeaconNode.tsx
src/renderer/ducks/beacon/sagas.ts
src/renderer/services/eth2/client/eth2ApiClient/index.ts

Fix add remote beacon error's

---

src/renderer/ducks/auth/actions.ts
src/renderer/ducks/auth/sagas.ts
src/renderer/ducks/beacon/sagas.ts
src/renderer/ducks/register/sagas.ts
src/renderer/ducks/validator/sagas.ts

Fix validator add and remove

---

src/renderer/containers/Validator/Validator.tsx
src/renderer/ducks/validator/actions.ts
src/renderer/ducks/validator/sagas.ts
src/renderer/ducks/validator/slice.ts

Autostart validator

---

src/renderer/GlobalLoader.tsx
src/renderer/app.tsx
src/renderer/containers/Onboard/CreatePassword/CreatePasswordContainer.tsx
src/renderer/ducks/beacon/sagas.ts
src/renderer/ducks/reducers.ts
src/renderer/ducks/settings/actions.ts
src/renderer/ducks/settings/selectors.ts
src/renderer/ducks/settings/slice.ts
src/renderer/ducks/validator/sagas.ts

Add loaders

---

src/renderer/containers/ValidatorDetails/ValidatorStats/ValidatorStats.tsx
src/renderer/ducks/validator/sagas.ts

Fix validator buttons

---

src/renderer/components/LogStream/logstream.scss
src/renderer/services/eth2/client/eth2ApiClient/cgEth2ValidatorApi.tsx
src/renderer/services/eth2/client/logger.ts
src/renderer/services/utils/logging/buffered.ts

Format logs

---

.github/workflows/release.yaml

Generate changelog

---

.github/workflows/release.yaml

Fix changelog generation

---

src/main/menu/menu.ts
src/renderer/ducks/auth/sagas.ts
test/e2e/redux/auth/sagas.spec.ts

Fix dashboard infinity loading

---

.github/workflows/release.yaml
electron-builder.yml
osx/entitlements.mac.plist
package.json
yarn.lock

- _EXAMPLE - Removed basic auth from the controller_
Closes #

Add mac notarization

---

electron-builder.yml
osx/entitlements.mac.plist

- _EXAMPLE - Removed basic auth from the controller_
Closes #

Add library validation entitlement

---

package.json

Release 0.5.3

---

.github/workflows/release.yaml

- _EXAMPLE - Removed basic auth from the controller_
Closes #

Fix sentry sourcemap

---

.env.dist
lighthouse-testnet.yml
src/renderer/services/eth2/networks/local.ts
teku-testnet.yml
testnet/teku/start.sh
testnet/teku/vars.env

Teku testnet

---

.github/workflows/release.yaml
src/renderer/ducks/beacon/sagas.ts
yarn.lock

- fix overlapping
- fix overlapping
Closes #531

Fix modal and loader overlapping

---

src/renderer/components/ConfigureBeaconNode/ConfigureBeaconNode.tsx
src/renderer/containers/AddBeaconNode/AddBeaconNode.tsx
src/renderer/ducks/beacon/sagas.ts
src/renderer/services/docker/type.ts
src/renderer/services/docker/utils.ts
src/renderer/services/eth2/client/defaults.ts
src/renderer/services/eth2/client/lighthouse/defaults.ts
test/unit/services/docker/DockerCommand.spec.ts
test/unit/services/docker/DockerRunParams.spec.ts

- implement docker ram limit option
- implement docker ram limit UI
- implement docker ram limit param
- small refactor
Closes #544

Max docker container ram

---

src/renderer/ducks/validator/sagas.ts
src/renderer/services/utils/getValidatorStatus.ts
src/renderer/services/utils/validator.ts
test/e2e/redux/validator/getAttestationEffectiveness/testAttestationEffectivenessSaga.ts

Fix clients

---

src/config/config.ts
src/main/menu/menu.ts
src/renderer/components/ConfigureBeaconNode/ConfigureBeaconNode.tsx

- change default path for beacon node data
- fix mac os logs folder navigation

Fix log locations

---

src/renderer/ducks/beacon/sagas.ts

fix permission issue
